Add continuous integration tests
Nercury/android_logger-rs pull request #42
Opened 2021-04-12 14:42 UTC by BramBonne

Runs tests on every push and pull request.

Additionally, this bumps the version number to trigger the tests to be picked up by AOSP's automatic importer.

2021-04-12 21:12 UTC, Dushistov commented on .github/workflows/ci.yaml
> +name: Continuous integration
There is travis CI enabled for this repo: https://github.com/Nercury/android_logger-rs/blob/master/.travis.yml .
I suppose migration to github actions is ok, but we need at least convert all checks from travis to github actions.

2021-04-12 21:13 UTC, Dushistov requested changes
There is travis CI enabled for this repo: https://github.com/Nercury/android_logger-rs/blob/master/.travis.yml .
I suppose migration to github actions is ok, but we need at least convert all checks from travis to github actions.

2021-04-13 08:50 UTC, BramBonne commented
Thanks for the review! I totally missed the existing Travis CI checks.

I moved everything over to GitHub actions for now, but please let me know if you prefer it when I'd just add the tests to the Travis CI instead.

2021-04-13 09:09 UTC, Dushistov commented
Looks like without enabled github actions for repo it is impossible to test your PR,
so I created #43 . It enabled github actions for this repo when merged, and you rebase your PR,
I suppose we see results of github actions for this PR.

2021-04-13 09:15 UTC, BramBonne commented
Sounds good!

Alternatlively, you can see my PR in action at https://github.com/BramBonne/android_logger-rs/actions as well, as it's been merged there already.

2021-04-15 10:42 UTC, Dushistov approved these changes
Not sure about version bump, this is depend on @Nercury . 
But otherwise looks good.

2021-04-15 11:38 UTC, Nercury commented
This should probably only need a patch version change if the API is exactly the same. But there aren't yet many users of `0.11` version, so it's fine in this case.

2021-04-15 11:45 UTC, Nercury commented
Let's also remove travis.

2021-04-15 11:53 UTC, BramBonne commented
Thanks for taking a look! I changed the new version number to 0.10.1 now.

As for Travis, I removed the `.travis.yml` file in the previous patch already; is any additional action required to prevent it from triggering?

2021-04-15 20:23 UTC, merged

2021-04-15 20:23 UTC, Nercury commented
I am going to sort that travis out.