Fix bug only values equal to the set level are logged
Nercury/android_logger-rs pull request #62
Opened 2022-12-29 07:30 UTC by TiggeZaki

The document says that if `Warn` is set, `Error` will also be logged, but not `Info`. But in fact, if `Warn` is set, only `Warn` is logged, not `Error`.
I think this is a bug caused by the comparison operator.

2022-12-29 08:46 UTC, MarijnS95 commented
Looks like this was introduced two weeks ago: #51

Besides, this should probably use [`LevelFilter`](https://docs.rs/log/latest/log/enum.LevelFilter.html).

2022-12-30 13:53 UTC, tyranron requested changes
@TiggeZaki could you rework it with using `LevelFilter` in config?

2023-01-02 06:47 UTC, TiggeZaki commented
@tyranron PTAL😀

2023-01-19 13:48 UTC, tyranron approved these changes
@TiggeZaki sorry for the late response. Thank you for taking time to fix this!

I've bikeshedded your solution in the following ways:
1. Restored `log_level` field `Option`ality to preserve previous semantics of piggy-backing log level filtering on to `log` crate, if it's not set.
2. Renamed new method to `set_max_level()` to comply with the similar one `log::set_max_level()`.

2023-01-19 13:50 UTC, merged

2023-01-19 14:08 UTC, tyranron commented
@TiggeZaki @MarijnS95 released in [0.12.0](https://github.com/Nercury/android_logger-rs/releases/tag/v0.12.0).

2023-01-19 14:13 UTC, MarijnS95 commented on CHANGELOG.md
> +- `Config::with_max_level()` method to filters logs via `log::LevelFilter`. ([#62])
`filters` or `to filter`?

2023-01-19 14:13 UTC, MarijnS95 commented on CHANGELOG.md
> +- Incorrect logs level filtering. ([#62])
`log`*

2023-01-19 14:14 UTC, MarijnS95 commented
@tyranron thanks, looks much better that way! I would've bike-shedded some plural issues in the changelog, but the release is already out :no_mouth: